#!/usr/bin/env node
/**
 * Print idempotent SQL that narrows non-admin Directus wildcard field
 * permissions.
 *
 * Run this after broader Studio setup scripts. It intentionally leaves the
 * Administrator policy untouched, but replaces `fields = '*'` for editor,
 * importer and service-import policies with explicit allowlists.
 *
 * Usage:
 *   node scripts/setup_directus_technical_permissions_sql.mjs > /tmp/isvoi_setup_directus_technical_permissions_sql.sql
 *   cd infra/directus-beget
 *   set -a && . ./.env && set +a
 *   docker compose exec -T database psql -U "$DB_USER" -d "$DB_DATABASE" -v ON_ERROR_STOP=1 < /tmp/isvoi_setup_directus_technical_permissions_sql.sql
 */

const fields = {
  devices: [
    "id",
    "status",
    "stock_status",
    "content_status",
    "sort",
    "category",
    "title",
    "model",
    "specs",
    "storage",
    "color",
    "serial",
    "price",
    "price_text",
    "grade",
    "battery",
    "battery_text",
    "meta_battery",
    "warranty",
    "warranty_text",
    "exit",
    "exit_text",
    "availability",
    "short_description",
    "headline",
    "listing_file",
    "listing_image",
    "listing_alt",
    "cta_label",
    "has_detail_page",
    "detail_href",
    "visual_class",
    "gallery",
    "passport",
    "trade",
    "source_system",
    "source_id",
    "import_batch",
    "imported_at",
    "admin_note",
    "created_at",
    "updated_at",
  ].join(","),
  devicesCreate: [
    "id",
    "status",
    "stock_status",
    "content_status",
    "sort",
    "category",
    "title",
    "model",
    "specs",
    "storage",
    "color",
    "serial",
    "price",
    "price_text",
    "grade",
    "battery",
    "battery_text",
    "meta_battery",
    "warranty",
    "warranty_text",
    "exit",
    "exit_text",
    "availability",
    "short_description",
    "headline",
    "listing_image",
    "listing_alt",
    "cta_label",
    "has_detail_page",
    "detail_href",
    "visual_class",
    "source_system",
    "source_id",
    "import_batch",
    "imported_at",
    "admin_note",
  ].join(","),
  devicesUpdate: [
    "status",
    "stock_status",
    "content_status",
    "sort",
    "tags",
    "category",
    "title",
    "model",
    "specs",
    "storage",
    "color",
    "serial",
    "price",
    "price_text",
    "grade",
    "battery",
    "battery_text",
    "meta_battery",
    "warranty",
    "warranty_text",
    "exit",
    "exit_text",
    "availability",
    "short_description",
    "headline",
    "listing_file",
    "listing_image",
    "listing_alt",
    "cta_label",
    "has_detail_page",
    "detail_href",
    "visual_class",
    "source_system",
    "source_id",
    "import_batch",
    "imported_at",
    "admin_note",
  ].join(","),
  deviceImages: [
    "id",
    "status",
    "shot_status",
    "device",
    "role",
    "sort",
    "image",
    "label",
    "alt",
    "source_path",
    "import_batch",
    "created_at",
    "updated_at",
  ].join(","),
  deviceImageDelete: "id,device,image,role",
  devicePassports: [
    "id",
    "device",
    "repair",
    "water",
    "summary_rows",
    "diagnostics_status",
    "diagnostics_checklist",
    "condition_grade_text",
    "condition_note",
    "condition_notes",
    "defect_photo",
    "defect_photo_alt",
    "warranty_duration",
    "warranty_covered",
    "warranty_not_covered",
    "exit_headline",
    "exit_buy_today",
    "exit_trade_in_estimate",
    "exit_condition",
    "exit_note",
    "created_at",
    "updated_at",
  ].join(","),
  devicePassportsWrite: [
    "device",
    "repair",
    "water",
    "summary_rows",
    "diagnostics_status",
    "diagnostics_checklist",
    "condition_grade_text",
    "condition_note",
    "condition_notes",
    "defect_photo",
    "defect_photo_alt",
    "warranty_duration",
    "warranty_covered",
    "warranty_not_covered",
    "exit_headline",
    "exit_buy_today",
    "exit_trade_in_estimate",
    "exit_condition",
    "exit_note",
  ].join(","),
  tradeOptions: "id,device,value,label,sort,is_active,created_at,updated_at",
  tradeOptionsWrite: "device,value,label,sort,is_active",
  tradeOptionsDelete: "id,device,label",
  directusFilesRead: [
    "id",
    "storage",
    "filename_disk",
    "filename_download",
    "title",
    "description",
    "type",
    "filesize",
    "width",
    "height",
    "focal_point_x",
    "focal_point_y",
    "folder",
    "uploaded_on",
    "modified_on",
  ].join(","),
  directusFilesCreate: [
    "title",
    "description",
    "folder",
    "file",
    "tags",
    "filename_download",
    "filename_disk",
    "storage",
    "type",
    "filesize",
    "width",
    "height",
    "focal_point_x",
    "focal_point_y",
    "charset",
    "duration",
    "embed",
    "location",
    "tus_id",
    "tus_data",
    "metadata",
    "uploaded_by",
    "uploaded_on",
    "created_on",
    "modified_by",
    "modified_on",
  ].join(","),
  directusFilesUpdate: "title,description,folder,tags,focal_point_x,focal_point_y",
  directusFolders: "id,name,parent",
  catalogImportBatchesRead: [
    "id",
    "status",
    "batch_name",
    "workbook",
    "photos_archive",
    "default_status",
    "note",
    "last_run_mode",
    "last_run_status",
    "last_run_log",
    "last_run_at",
    "created_at",
    "updated_at",
  ].join(","),
  catalogImportBatchesOperatorWrite: "batch_name,workbook,photos_archive,default_status,note",
  catalogImportBatchesTechnicalWrite:
    "status,last_run_mode,last_run_status,last_run_log,last_run_at",
  catalogImportBatchesImporterWrite: [
    "status",
    "batch_name",
    "workbook",
    "photos_archive",
    "default_status",
    "note",
    "last_run_mode",
    "last_run_status",
    "last_run_log",
    "last_run_at",
  ].join(","),
  leads: [
    "id",
    "created_at",
    "updated_at",
    "kind",
    "status",
    "priority",
    "assigned_to",
    "contact_channel",
    "next_action_at",
    "last_contacted_at",
    "manager_note",
    "name",
    "contact",
    "device",
    "device_id",
    "scenario",
    "message",
    "source",
    "source_path",
    "source_url",
    "page_title",
    "referrer",
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_content",
    "utm_term",
    "user_agent",
    "comments",
  ].join(","),
  leadComments: "id,lead,created_at,updated_at,created_by,comment,outcome,next_action_at",
  siteSettings: [
    "id",
    "brand_name",
    "tagline",
    "city",
    "logo_file",
    "logo_alt",
    "logo_href",
    "logo_width",
    "logo_height",
    "logo_caption",
    "show_brand_name",
    "header_cta_label",
    "header_cta_url",
    "phone",
    "telegram",
    "email",
    "address",
    "default_og_image",
    "footer_legal",
    "footer_note",
    "footer_brand_text",
    "footer_copyright",
    "maintenance_mode",
  ].join(","),
  devicePageSettings: [
    "id",
    "singleton_key",
    "breadcrumb_home_label",
    "breadcrumb_home_href",
    "breadcrumb_catalog_label",
    "breadcrumb_catalog_href",
    "back_label",
    "grade_prefix",
    "updated_prefix",
    "available_label",
    "reserved_label",
    "sold_label",
    "price_note",
    "condition_title",
    "story_eyebrow",
    "story_fallback_title",
    "warranty_title",
    "warranty_duration_label",
    "exit_price_label",
    "warranty_covered_label",
    "warranty_not_covered_label",
    "warranty_covered_fallback",
    "warranty_not_covered_fallback",
    "warranty_duration_fallback",
    "trade_title",
    "trade_value_prefix",
    "trade_cta_label",
    "trade_cta_href",
    "related_eyebrow",
    "related_title",
    "related_cta_label",
    "related_cta_href",
    "related_prompt_title",
    "related_prompt_body",
    "related_prompt_cta_label",
    "related_prompt_cta_href",
    "related_prompt_cues",
    "passport_eyebrow",
    "passport_title",
    "passport_body",
    "passport_diagnostics_title",
    "passport_status_prefix",
    "passport_status_fallback",
    "passport_verified_label",
    "mobile_reserved_label",
    "mobile_sold_label",
    "mobile_available_label",
    "mobile_trade_label",
    "mobile_nav_aria_label",
  ].join(","),
  devicePageSettingsWrite: [
    "breadcrumb_home_label",
    "breadcrumb_home_href",
    "breadcrumb_catalog_label",
    "breadcrumb_catalog_href",
    "back_label",
    "grade_prefix",
    "updated_prefix",
    "available_label",
    "reserved_label",
    "sold_label",
    "price_note",
    "condition_title",
    "story_eyebrow",
    "story_fallback_title",
    "warranty_title",
    "warranty_duration_label",
    "exit_price_label",
    "warranty_covered_label",
    "warranty_not_covered_label",
    "warranty_covered_fallback",
    "warranty_not_covered_fallback",
    "warranty_duration_fallback",
    "trade_title",
    "trade_value_prefix",
    "trade_cta_label",
    "trade_cta_href",
    "related_eyebrow",
    "related_title",
    "related_cta_label",
    "related_cta_href",
    "related_prompt_title",
    "related_prompt_body",
    "related_prompt_cta_label",
    "related_prompt_cta_href",
    "related_prompt_cues",
    "passport_eyebrow",
    "passport_title",
    "passport_body",
    "passport_diagnostics_title",
    "passport_status_prefix",
    "passport_status_fallback",
    "passport_verified_label",
    "mobile_reserved_label",
    "mobile_sold_label",
    "mobile_available_label",
    "mobile_trade_label",
    "mobile_nav_aria_label",
  ].join(","),
  navigationItems:
    "id,label,label_short,aria_label,link_type,page,section_anchor,custom_url,url,location,parent,children,sort,is_active,open_in_new,item_role,icon",
  faqItems: "id,key,question,answer,page,category,sort,is_active",
  sitePages: "id,slug,template,status,title,meta_description,og_image,sections",
  pageSections: [
    "id",
    "page",
    "section_key",
    "variant",
    "eyebrow",
    "headline",
    "subheadline",
    "body",
    "primary_cta_label",
    "primary_cta_url",
    "secondary_cta_label",
    "secondary_cta_url",
    "image",
    "sort_order",
    "is_active",
    "content",
  ].join(","),
};

const updates = [
  ["ISVOI Editor", "catalog_import_batches", "read", fields.catalogImportBatchesRead],
  ["ISVOI Editor", "devices", "read", fields.devices],
  ["ISVOI Editor", "device_images", "read", fields.deviceImages],
  ["ISVOI Editor", "device_passports", "read", fields.devicePassports],
  ["ISVOI Editor", "device_passports", "create", fields.devicePassportsWrite],
  ["ISVOI Editor", "device_passports", "update", fields.devicePassportsWrite],
  ["ISVOI Editor", "trade_options", "read", fields.tradeOptions],
  ["ISVOI Editor", "trade_options", "create", fields.tradeOptionsWrite],
  ["ISVOI Editor", "trade_options", "update", fields.tradeOptionsWrite],
  ["ISVOI Editor", "directus_folders", "read", fields.directusFolders],
  ["ISVOI Editor", "faq_items", "read", fields.faqItems],
  ["ISVOI Editor", "lead_comments", "read", fields.leadComments],
  ["ISVOI Editor", "leads", "read", fields.leads],
  ["ISVOI Editor", "navigation_items", "read", fields.navigationItems],
  ["ISVOI Editor", "page_sections", "read", fields.pageSections],
  ["ISVOI Editor", "site_pages", "read", fields.sitePages],
  ["ISVOI Editor", "site_settings", "read", fields.siteSettings],
  ["ISVOI Editor", "device_page_settings", "read", fields.devicePageSettings],
  ["ISVOI Editor", "device_page_settings", "update", fields.devicePageSettingsWrite],
  ["ISVOI Editor", "directus_files", "read", fields.directusFilesRead],
  ["ISVOI Editor", "directus_files", "create", fields.directusFilesCreate],
  ["ISVOI Editor", "directus_files", "update", fields.directusFilesUpdate],

  ["ISVOI Importer", "catalog_import_batches", "read", fields.catalogImportBatchesRead],
  ["ISVOI Importer", "catalog_import_batches", "create", fields.catalogImportBatchesImporterWrite],
  ["ISVOI Importer", "catalog_import_batches", "update", fields.catalogImportBatchesImporterWrite],
  ["ISVOI Importer", "devices", "read", fields.devices],
  ["ISVOI Importer", "devices", "create", fields.devicesCreate],
  ["ISVOI Importer", "devices", "update", fields.devicesUpdate],
  ["ISVOI Importer", "device_images", "read", fields.deviceImages],
  ["ISVOI Importer", "device_images", "create", fields.deviceImages],
  ["ISVOI Importer", "device_images", "update", fields.deviceImages],
  ["ISVOI Importer", "device_passports", "read", fields.devicePassports],
  ["ISVOI Importer", "device_passports", "create", fields.devicePassportsWrite],
  ["ISVOI Importer", "device_passports", "update", fields.devicePassportsWrite],
  ["ISVOI Importer", "trade_options", "read", fields.tradeOptions],
  ["ISVOI Importer", "trade_options", "create", fields.tradeOptionsWrite],
  ["ISVOI Importer", "trade_options", "update", fields.tradeOptionsWrite],
  ["ISVOI Importer", "directus_files", "read", fields.directusFilesRead],
  ["ISVOI Importer", "directus_files", "create", fields.directusFilesCreate],
  ["ISVOI Importer", "directus_files", "update", fields.directusFilesUpdate],
  ["ISVOI Importer", "directus_folders", "read", fields.directusFolders],

  ["ISVOI Catalog Import", "catalog_import_batches", "read", fields.catalogImportBatchesRead],
  [
    "ISVOI Catalog Import",
    "catalog_import_batches",
    "update",
    fields.catalogImportBatchesTechnicalWrite,
  ],
  ["ISVOI Catalog Import", "devices", "read", fields.devices],
  ["ISVOI Catalog Import", "devices", "create", fields.devicesCreate],
  ["ISVOI Catalog Import", "devices", "update", fields.devicesUpdate],
  ["ISVOI Catalog Import", "device_images", "read", fields.deviceImages],
  ["ISVOI Catalog Import", "device_images", "create", fields.deviceImages],
  ["ISVOI Catalog Import", "device_images", "update", fields.deviceImages],
  ["ISVOI Catalog Import", "device_images", "delete", fields.deviceImageDelete],
  ["ISVOI Catalog Import", "device_passports", "read", fields.devicePassports],
  ["ISVOI Catalog Import", "device_passports", "create", fields.devicePassportsWrite],
  ["ISVOI Catalog Import", "device_passports", "update", fields.devicePassportsWrite],
  ["ISVOI Catalog Import", "trade_options", "read", fields.tradeOptions],
  ["ISVOI Catalog Import", "trade_options", "create", fields.tradeOptionsWrite],
  ["ISVOI Catalog Import", "trade_options", "update", fields.tradeOptionsWrite],
  ["ISVOI Catalog Import", "trade_options", "delete", fields.tradeOptionsDelete],
  ["ISVOI Catalog Import", "directus_files", "read", fields.directusFilesRead],
  ["ISVOI Catalog Import", "directus_files", "create", fields.directusFilesCreate],
  ["ISVOI Catalog Import", "directus_files", "update", fields.directusFilesUpdate],
  ["ISVOI Catalog Import", "directus_folders", "read", fields.directusFolders],
];

function sql(value) {
  if (value == null) return "NULL";
  return `'${String(value).replaceAll("'", "''")}'`;
}

const lines = [
  "BEGIN;",
  "",
  "CREATE OR REPLACE FUNCTION isvoi_set_permission_fields(",
  "  p_policy_name text,",
  "  p_collection varchar,",
  "  p_action varchar,",
  "  p_fields text",
  ") RETURNS void",
  "LANGUAGE plpgsql",
  "AS $$",
  "DECLARE",
  "  v_policy uuid;",
  "BEGIN",
  "  SELECT id INTO v_policy FROM directus_policies WHERE name = p_policy_name LIMIT 1;",
  "  IF v_policy IS NULL THEN",
  "    RETURN;",
  "  END IF;",
  "",
  "  UPDATE directus_permissions",
  "  SET fields = p_fields",
  "  WHERE policy = v_policy",
  "    AND collection = p_collection",
  "    AND action = p_action;",
  "END;",
  "$$;",
  "",
  "CREATE OR REPLACE FUNCTION isvoi_delete_permission(",
  "  p_policy_name text,",
  "  p_collection varchar,",
  "  p_action varchar",
  ") RETURNS void",
  "LANGUAGE plpgsql",
  "AS $$",
  "DECLARE",
  "  v_policy uuid;",
  "BEGIN",
  "  SELECT id INTO v_policy FROM directus_policies WHERE name = p_policy_name LIMIT 1;",
  "  IF v_policy IS NULL THEN",
  "    RETURN;",
  "  END IF;",
  "",
  "  DELETE FROM directus_permissions",
  "  WHERE policy = v_policy",
  "    AND collection = p_collection",
  "    AND action = p_action;",
  "END;",
  "$$;",
  "",
];

for (const [policy, collection, action, fieldList] of updates) {
  lines.push(
    `SELECT isvoi_set_permission_fields(${sql(policy)}, ${sql(collection)}, ${sql(action)}, ${sql(fieldList)});`,
  );
}

const destructiveStudioDeletes = [
  ["ISVOI Editor", "device_images", "delete"],
  ["ISVOI Editor", "trade_options", "delete"],
  ["ISVOI Importer", "device_images", "delete"],
  ["ISVOI Importer", "trade_options", "delete"],
];

lines.push("");
for (const [policy, collection, action] of destructiveStudioDeletes) {
  lines.push(`SELECT isvoi_delete_permission(${sql(policy)}, ${sql(collection)}, ${sql(action)});`);
}

lines.push(
  "",
  "DROP FUNCTION isvoi_set_permission_fields(text, varchar, varchar, text);",
  "DROP FUNCTION isvoi_delete_permission(text, varchar, varchar);",
  "",
  "SELECT 'technical_permissions.non_admin_wildcards' AS check_name, count(*)::text AS value",
  "FROM directus_permissions pe",
  "JOIN directus_policies p ON p.id = pe.policy",
  "WHERE pe.fields = '*'",
  "  AND p.name IN ('ISVOI Editor', 'ISVOI Importer', 'ISVOI Catalog Import')",
  "UNION ALL",
  "SELECT 'technical_permissions.import_policy_updates', count(*)::text",
  "FROM directus_permissions pe",
  "JOIN directus_policies p ON p.id = pe.policy",
  "WHERE p.name IN ('ISVOI Importer', 'ISVOI Catalog Import')",
  "  AND pe.collection IN ('devices', 'device_images', 'device_passports', 'trade_options', 'directus_files', 'directus_folders', 'catalog_import_batches')",
  "  AND pe.fields <> '*'",
  "UNION ALL",
  "SELECT 'technical_permissions.editor_updates', count(*)::text",
  "FROM directus_permissions pe",
  "JOIN directus_policies p ON p.id = pe.policy",
  "WHERE p.name = 'ISVOI Editor'",
  "  AND pe.collection IN ('devices', 'device_images', 'device_passports', 'trade_options', 'directus_folders', 'faq_items', 'lead_comments', 'leads', 'navigation_items', 'page_sections', 'site_pages', 'site_settings', 'device_page_settings', 'catalog_import_batches')",
  "  AND pe.fields <> '*';",
  "",
  "COMMIT;",
);

process.stdout.write(`${lines.join("\n")}\n`);
