// Runs only inside the disposable native Directus production-policy contract.
import assert from 'node:assert/strict';
import { conversationsSql } from './setup_directus_telegram_conversations_sql.mjs';
import { notificationsSql } from './setup_directus_telegram_notifications_sql.mjs';
import { notificationsContract } from './telegram_notifications_contract.mjs';
import { createHandlers } from '../infra/directus-beget/extensions-bundled/directus-extension-isvoi-telegram/src/index.js';
export async function conversationsContract({db,ItemsService,getSchema,p,adminRole}) {
  const id=n=>`66666666-6666-4666-8666-${String(n).padStart(12,'0')}`;
  const editorPolicy=id(90);
  const editorRole=id(91),editorUser=id(92),editorAccess=id(93);
  await db('directus_policies').insert({id:editorPolicy,name:'ISVOI Editor',admin_access:false,app_access:true});
  await db('directus_roles').insert({id:editorRole,name:'ISVOI Editor'});
  await db('directus_users').insert({id:editorUser,role:editorRole,status:'active'});
  await db('directus_access').insert({id:editorAccess,role:editorRole,policy:editorPolicy});
  await db('directus_permissions').insert({policy:editorPolicy,collection:'leads',action:'read',fields:'id,status'});
  await db.raw(conversationsSql);await db.raw(conversationsSql);await db.raw(notificationsSql);await db.raw(notificationsSql);
  const dialogsField=await db('directus_fields').where({collection:'leads',field:'telegram_dialogs'}).first();
  assert.equal(dialogsField.special,'o2m');assert.equal(dialogsField.readonly,false);
  assert.equal((await db('directus_fields').where({collection:'lead_conversations',field:'messages'}).first()).special,'o2m');
  assert.equal((await db('directus_relations').where({many_collection:'lead_conversations',many_field:'lead_id'}).first()).one_field,'telegram_dialogs');
  assert.equal((await db('directus_relations').where({many_collection:'lead_messages',many_field:'conversation_id'}).first()).one_field,'messages');
  const salesGroup=await db('directus_collections').where({collection:'isvoi_sales'}).first();
  assert.equal((await db('directus_collections').where({collection:'lead_conversations'}).first()).group,salesGroup?'isvoi_sales':null);
  const editorLeadRead=await db('directus_permissions').where({policy:editorPolicy,collection:'leads',action:'read'}).first();
  assert.ok(editorLeadRead.fields.split(',').includes('telegram_dialogs'));
  assert.ok(await db('directus_permissions').where({policy:editorPolicy,collection:'lead_messages',action:'read'}).first());
  const campaignUpdate=await db('directus_permissions').where({policy:editorPolicy,collection:'telegram_campaigns',action:'update'}).first();
  assert.ok(campaignUpdate);
  assert.equal(campaignUpdate.fields.includes('approved_by'),false);
  assert.equal(campaignUpdate.fields.includes('approved_at'),false);
  await db.raw('ALTER TABLE leads ADD contact text, ADD contact_channel text, ADD message text, ADD source text, ADD source_path text');
  const intake=id(1),role=id(2),policy=id(3);
  await db('directus_roles').insert({id:role,name:'Website intake fixture'});
  await db('directus_users').insert({id:intake,role,status:'active'});
  await db('directus_policies').insert({id:policy,name:'Website intake fixture',admin_access:false,app_access:false});
  await db('directus_access').insert({id:id(4),role,policy});
  await db('directus_permissions').insert({policy,collection:'leads',action:'create',fields:'id,kind,status,contact_channel,contact,source,source_path,message,store_location_id,is_test,reference_code',permissions:{},validation:{status:{_eq:'new'},is_test:{_eq:false}}});
  const env={ISVOI_TELEGRAM_ENABLED:true,ISVOI_TELEGRAM_BOT_ID:p.botId,ISVOI_TELEGRAM_WORKER_USER_ID:p.worker,ISVOI_TELEGRAM_MODE:'production',PUBLIC_URL:'https://api.example.test',ISVOI_TELEGRAM_CONVERSATIONS_ENABLED:true,ISVOI_TELEGRAM_NOTIFICATIONS_ENABLED:true,ISVOI_TELEGRAM_INTAKE_USER_ID:intake,ISVOI_TELEGRAM_BOT_USERNAME:'fixture_test_bot'};
  const h=createHandlers({database:db,services:{ItemsService},getSchema:()=>getSchema({bypassCache:true}),env});
  const identity={bot_id:p.botId,worker_id:id(5)};
  await db('telegram_runtime').where({bot_id:p.botId}).update({lease_until:db.raw("now()-interval '1 minute'")});
  const req=body=>({accountability:{user:p.worker,admin:false},body:{...identity,...body}});
  await h.session(req({}));
  const site=body=>h.intake({accountability:{user:intake,admin:false},body:{kind:'selection',status:'new',contact:'technical fixture',is_test:false,store_location_id:p.store,...body}});
  assert.deepEqual(await h['intake-check']({accountability:{user:intake,admin:false},body:{}}),{ok:true});
  await assert.rejects(h.intake({accountability:{user:p.worker},body:{}}),e=>e.publicCode==='FORBIDDEN');
  await assert.rejects(h.intake({accountability:{user:intake,admin:true},body:{}}),e=>e.publicCode==='FORBIDDEN');
  await assert.rejects(h['intake-check']({accountability:{user:p.worker,admin:false},body:{}}),e=>e.publicCode==='FORBIDDEN');
  await assert.rejects(site({assigned_to:p.staff}),e=>e.code==='FORBIDDEN');
  const created=await site({reference_code:'CHAT-FIXTURE'});
  const token=new URL(created.telegram_url).searchParams.get('start');
  assert.equal(token.length,43);
  assert.equal((await db('telegram_link_tokens').first()).token_hash.includes(token),false);
  let sequence=1000,telegramId=1000;
  const client=123456700,other=123456701;
  const privateMessage=(text,user=client,extra={})=>({update_id:++sequence,message:{message_id:++telegramId,chat:{type:'private',id:user},from:{id:user,is_bot:false},text,...extra}});
  const apply=u=>h.update(req({update:u}));
  const start=privateMessage(`/start ${token}`);
  assert.equal((await apply(start)).result,'linked');
  assert.equal((await apply(start)).result,'linked');
  assert.equal((await apply(privateMessage(`/start ${token}`,other))).result,'invalid_link');
  const c=await db('lead_conversations').where({lead_id:created.id}).first();
  assert.equal(String(c.client_user_id),String(client));
  assert.equal(Number((await db('lead_conversations').where({lead_id:created.id}).count('* as n').first()).n),1);
  const incoming=privateMessage('Хочу уточнить наличие');
  await apply(incoming);await apply(incoming);
  assert.equal(Number((await db('lead_messages').where({conversation_id:c.id,direction:'in'}).count('* as n').first()).n),1);
  assert.equal((await db('leads').where({id:created.id}).first()).telegram_unread,true);
  await apply(privateMessage('',client,{photo:[{file_id:'photo_fixture_1'}],caption:'Фото',media_group_id:'album_fixture'}));
  assert.equal((await db('lead_messages').where({conversation_id:c.id,photo_file_id:'photo_fixture_1'}).first()).album_id,'album_fixture');
  const card=await db('telegram_deliveries').where({lead_id:created.id}).first();
  await db('telegram_deliveries').where({id:card.id}).update({topic_id:500,message_id:501,state:'done',sent_revision:1});
  await db('leads').where({id:created.id}).update({assigned_to:p.staff,status:'in_progress'});
  // Other stage-1 deliveries have been tested above; isolate this fixture's message queue.
  await db('telegram_deliveries').update({state:'done'});
  const complete=(job,outcome)=>h.complete(req({id:job.id,operation_id:job.operation_id,channel:job.channel,outcome:outcome??(job.method==='createForumTopic'?{type:'ok',topic_id:++telegramId}:job.method==='editMessageText'?{type:'ok',message_id:job.payload.message_id}:{type:'ok',message_id:++telegramId})}));
  async function next() {await db('telegram_runtime').where({bot_id:p.botId}).update({send_after:db.fn.now()});return (await h.next(req({}))).job;}
  async function drain() {let job;for(let n=0;n<30 && (job=await next());n++) await complete(job);}
  await drain();
  const group=(text,extra={})=>({update_id:++sequence,message:{message_id:++telegramId,message_thread_id:500,chat:{id:Number(p.chatId),type:'supergroup'},from:{id:Number(p.telegramUserId),is_bot:false},text,...extra}});
  assert.equal((await apply(group('Внутренний комментарий: скидку пока не обещаем'))).result,'internal');
  assert.equal(Number((await db('lead_messages').where({direction:'out'}).count('* as n').first()).n),0);
  const source=await db('telegram_message_outbox').where({conversation_id:c.id,destination:'group',state:'done'}).first();
  const click=(data,messageId,user=Number(p.telegramUserId),topic=500)=>({update_id:++sequence,callback_query:{id:`chat-${sequence}`,data,from:{id:user,is_bot:false},message:{message_id:Number(messageId),message_thread_id:topic,chat:{id:Number(p.chatId),type:'supergroup'},from:{id:Number(p.botId),is_bot:true}}}});
  assert.equal((await apply(click(`reply:${c.id}`,source.telegram_message_id,other))).result,'forbidden');
  assert.equal((await apply(click(`reply:${c.id}`,source.telegram_message_id,Number(p.telegramUserId),900))).result,'stale');
  assert.equal((await apply(click(`reply:${c.id}`,source.telegram_message_id))).result,'draft_started');await drain();
  let draft=await db('telegram_reply_drafts').where({conversation_id:c.id,state:'awaiting'}).first();
  await apply(group('Есть в наличии',{reply_to_message:{message_id:Number(draft.prompt_message_id)}}));await drain();
  draft=await db('telegram_reply_drafts').where({id:draft.id}).first();
  assert.equal(draft.state,'preview');
  const send=click(`send:${draft.id}`,draft.preview_message_id);
  assert.equal((await apply(send)).result,'queued');assert.equal((await apply(send)).result,'queued');
  assert.equal((await apply(click(`send:${draft.id}`,draft.preview_message_id))).result,'stale');
  assert.equal(Number((await db('lead_messages').where({conversation_id:c.id,direction:'out'}).count('* as n').first()).n),1);
  assert.equal((await db('lead_comments').where({lead:created.id}).first()).created_by,p.staff);
  const reply=await next();assert.equal(reply.destination,'client');assert.equal(reply.payload.chat_id,String(client));assert.equal(reply.payload.text,'Есть в наличии');
  await complete(reply,{type:'unknown'});await complete(reply,{type:'unknown'});
  assert.equal((await db('telegram_message_outbox').where({id:reply.id}).first()).state,'uncertain');
  assert.equal((await db('leads').where({id:created.id}).first()).telegram_unread,true);
  await drain();assert.equal(await next(),null);
  // A successful reply leaves a fresh contextual action at the bottom of the topic.
  assert.equal((await apply(click(`reply:${c.id}`,source.telegram_message_id))).result,'draft_started');await drain();
  draft=await db('telegram_reply_drafts').where({conversation_id:c.id,state:'awaiting'}).first();
  await apply(group('Дополнение к ответу',{reply_to_message:{message_id:Number(draft.prompt_message_id)}}));await drain();
  draft=await db('telegram_reply_drafts').where({id:draft.id}).first();
  assert.equal((await apply(click(`send:${draft.id}`,draft.preview_message_id))).result,'queued');
  const deliveredReply=await next();assert.equal(deliveredReply.destination,'client');assert.equal(deliveredReply.payload.text,'Дополнение к ответу');
  await complete(deliveredReply);
  assert.equal((await db('leads').where({id:created.id}).first()).telegram_unread,false);
  const followupNotice=await next();assert.equal(followupNotice.destination,'group');
  assert.deepEqual(followupNotice.payload.reply_markup.inline_keyboard,[[{text:'Написать ещё',callback_data:`reply:${c.id}`}]]);
  await complete(followupNotice);assert.equal(await next(),null);
  // Expired capability cannot bind a different lead.
  const expired=await site({reference_code:'CHAT-EXPIRED'});
  await db('telegram_link_tokens').where({lead_id:expired.id}).update({expires_at:db.raw("now()-interval '1 minute'")});
  assert.equal((await apply(privateMessage(`/start ${new URL(expired.telegram_url).searchParams.get('start')}`,other))).result,'invalid_link');
  // A revoked staff binding cannot turn a preview into an outgoing message.
  await apply(click(`reply:${c.id}`,source.telegram_message_id));await db('telegram_deliveries').update({state:'done'});await drain();
  draft=await db('telegram_reply_drafts').where({conversation_id:c.id,state:'awaiting'}).first();
  await apply(group('Не должно уйти',{reply_to_message:{message_id:Number(draft.prompt_message_id)}}));await drain();
  draft=await db('telegram_reply_drafts').where({id:draft.id}).first();
  await db('telegram_staff').where({id:p.staffBinding}).update({enabled:false});
  assert.equal((await apply(click(`send:${draft.id}`,draft.preview_message_id))).result,'forbidden');
  await db('telegram_staff').where({id:p.staffBinding}).update({enabled:true});
  await db('leads').where({id:created.id}).update({status:'closed'});
  const leadsBeforeContinuation=Number((await db('leads').count('* as n').first()).n);
  assert.equal((await apply(privateMessage('Новый вопрос после закрытия'))).result,'received');
  assert.equal((await db('leads').where({id:created.id}).first()).status,'closed');
  assert.equal(Number((await db('leads').count('* as n').first()).n),leadsBeforeContinuation+1);
  const continuationLead=await db('leads').where({contact:`telegram:${client}`,status:'new',kind:'support'}).first();
  assert.ok(continuationLead);
  const continuation=await db('lead_conversations').where({lead_id:continuationLead.id}).first();
  assert.notEqual(continuation.id,c.id);
  assert.equal((await db('lead_messages').where({conversation_id:continuation.id,direction:'in'}).first()).text,'Новый вопрос после закрытия');
  assert.equal((await db('telegram_client_sessions').where({bot_id:p.botId,user_id:client}).first()).conversation_id,continuation.id);
  // Direct entry creates no lead until a category and substantive message have both arrived.
  const before=Number((await db('leads').count('* as n').first()).n);
  await apply(privateMessage('/new',other));await db('telegram_deliveries').update({state:'done'});await drain();
  const s=await db('telegram_client_sessions').where({bot_id:p.botId,user_id:other}).first();
  const menus=await db('telegram_message_outbox').where({session_id:s.id,state:'done'}).orderBy('created_at','desc');
  const menu=menus.find(row=>row.payload.reply_markup?.inline_keyboard?.flat().some(b=>b.callback_data==='kind:selection'));
  const privateClick=data=>({update_id:++sequence,callback_query:{id:`private-${sequence}`,data,from:{id:other,is_bot:false},message:{message_id:Number(menu.telegram_message_id),chat:{type:'private',id:other},from:{id:Number(p.botId),is_bot:true}}}});
  assert.equal((await apply(privateClick('kind:selection'))).result,'selected');
  assert.equal(Number((await db('leads').count('* as n').first()).n),before);
  const direct=privateMessage('Нужен телефон для работы',other);
  assert.equal((await apply(direct)).result,'received');await apply(direct);
  assert.equal(Number((await db('leads').count('* as n').first()).n),before+1);
  assert.equal((await db('leads').where({contact:`telegram:${other}`}).first()).kind,'selection');
  // Six months are counted from closure; reopening cancels the deletion clock.
  const directConversation=await db('lead_conversations').where({lead_id:(await db('leads').where({contact:`telegram:${other}`}).first()).id}).first();
  await db('leads').where({id:directConversation.lead_id}).update({status:'closed'});
  assert.ok((await db('lead_conversations').where({id:directConversation.id}).first()).closed_at);
  await db('leads').where({id:directConversation.lead_id}).update({status:'in_progress'});
  assert.equal((await db('lead_conversations').where({id:directConversation.id}).first()).closed_at,null);
  await db('leads').where({id:directConversation.lead_id}).update({status:'closed'});
  await db('lead_conversations').where({id:directConversation.id}).update({closed_at:db.raw("now()-interval '6 months 1 day'")});
  await db('telegram_client_sessions').where({bot_id:p.botId,user_id:other}).update({updated_at:db.raw("now()-interval '6 months 1 day'")});
  await db('telegram_link_tokens').where({bot_id:p.botId}).update({expires_at:db.raw("now()-interval '2 days'")});
  await db('telegram_receipts').where({bot_id:p.botId}).update({created_at:db.raw("now()-interval '6 months 1 day'")});
  await db('telegram_retention_settings').where({bot_id:p.botId}).update({next_run_at:db.fn.now()});
  await next();
  assert.equal(await db('lead_conversations').where({id:directConversation.id}).first(),undefined);
  assert.equal(await db('telegram_client_sessions').where({bot_id:p.botId,user_id:other}).first(),undefined);
  assert.equal(Number((await db('telegram_link_tokens').where({bot_id:p.botId}).count('* as n').first()).n),0);
  assert.equal(Number((await db('telegram_receipts').where({bot_id:p.botId}).count('* as n').first()).n),0);
  const retention=await db('telegram_retention_settings').where({bot_id:p.botId}).first();
  assert.equal(Number(retention.retention_months),6);
  assert.ok(Number(retention.last_conversations_deleted)>=1);
  await notificationsContract({db,h,req,p,next,complete,sequenceState:{update:sequence,message:telegramId}});
  console.log('PASS: conversations: Directus relations, one-use site binding, expiry, permissions, dedup, photo/album history, internal-message isolation, confirmed and follow-up replies, uncertain delivery, closed-lead continuation, direct entry and six-month retention.');
}
